name: ocr_sederhana
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # === OCR (Android/iOS – ML Kit) ===
  google_mlkit_text_recognition: ^0.15.0

  # === Kamera ===
  camera: ^0.11.2+1

  # === Web & util umum ===
  js: ^0.7.2 # untuk interop Tesseract.js di web
  image_picker: ^1.0.7 # fallback web/mobile ambil gambar
  path_provider: ^2.1.2
  path: ^1.8.3

  # === Izin runtime (Android) ===
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
